apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-problem-detector-debug
  namespace: openstack
  labels:
    app: node-problem-detector-debug
spec:
  selector:
    matchLabels:
      app: node-problem-detector-debug
  template:
    metadata:
      labels:
        app: node-problem-detector-debug
    spec:
      hostNetwork: true  # 启用节点网络模式
      containers:
      - name: node-problem-detector
        command:
        - sleep
        - 100d
        # - /node-problem-detector
        # - --logtostderr
        # - --config.system-log-monitor=/config/kernel-monitor.json,/config/readonly-monitor.json,/config/docker-monitor.json
        image: docker.yylt.gq/altonzhu/dlv:go1.23.1
        # imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        ports:
        - containerPort: 32345
          hostPort: 32345
          name: dlv
          protocol: TCP
        securityContext:
          privileged: true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - mountPath: /tmp
          name: code
        - name: log
          mountPath: /var/log
          readOnly: true
        - name: kmsg
          mountPath: /dev/kmsg
          readOnly: true
        # Make sure node problem detector is in the same timezone
        # with the host.
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        # - name: config
        #   mountPath: /config
        #   readOnly: true
        - name: ipbin
          mountPath: /usr/sbin/ip
          readOnly: true
        - name: iplib
          mountPath: /lib64/libmnl.so.0
          readOnly: true
        - mountPath: /etc/ceph/ceph.conf
          name: ceph-etc
          readOnly: true
          subPath: ceph.conf
      nodeSelector:
        kubernetes.io/hostname: node-9
      # serviceAccountName: node-problem-detector
      volumes:
      - hostPath:
          path: /usr/sbin/ip
          type: File
        name: ipbin
      - hostPath:
          path: /lib64/libmnl.so.0
          type: File
        name: iplib
      - hostPath:
          path: /root/zt
          type: Directory
        name: code
      - name: log
        # Config `log` to your system log directory
        hostPath:
          path: /var/log/
      - name: kmsg
        hostPath:
          path: /dev/kmsg
      - name: localtime
        hostPath:
          path: /etc/localtime
      - configMap:
          defaultMode: 292
          name: ceph-etc
        name: ceph-etc
      # - name: config
      #   configMap:
      #     name: node-problem-detector-config
      #     items:
      #     - key: kernel-monitor.json
      #       path: kernel-monitor.json
      #     - key: readonly-monitor.json
      #       path: readonly-monitor.json
      #     - key: docker-monitor.json
      #       path: docker-monitor.json
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
